### PR TITLE
Update project dependencies and tooling

### PR DESCRIPTION
**Pull request by pedronveloso**
GSON version 2.7 brings many important bugfixes, and is on pair with the version other known libraries are using such as retrofit

### CODE REVIEW

**Comment by pedronveloso** [comment]
Took some extra work but it worked in the end :)

**Comment by waninkoko** [comment]
PR looks good to me, merged! Thank you very much.

**Comment by pedronveloso** [comment]
@waninkoko no worries. BTW you need to bump the version of the lib for this to become available right?

**Comment by waninkoko** [comment]
@pedronveloso Yep, but before I do that I'll do a general revision of the library. Anyway, if a developer wants to use the current pushed version, he just needs to change the artifact version to **3b183b7**

**Pull request merged**
